# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolyArea
                                 A QGIS plugin
 You choose a polygonial layer, and this plugin will add to its attributes a new column that has the area of each polygon
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-15
        copyright            : (C) 2021 by Ariel Turchinsky
        email                : ariel7590@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PolyArea class from file PolyArea.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .poly_area import PolyArea
    return PolyArea(iface)
